name: SBOM/SCA Scout

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
    inputs:
      docker_image:
        description: 'test scan'
        required: true
        default: 'ubuntu:20.04'

jobs:
  scout:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
      security-events: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to Dockerhub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set image to scan
        id: set-image
        run: |
          if [ -n "${{ github.event.inputs.docker_image }}" ]; then
            echo "IMAGE=${{ github.event.inputs.docker_image }}" >> $GITHUB_OUTPUT
          else
            echo "IMAGE=ubuntu:20.04" >> $GITHUB_OUTPUT
          fi

      # Pull the github input image or use the default
      - name: Pull the image
        run: docker pull ${{ steps.set-image.outputs.IMAGE }}

      - name: Docker Scout
        uses: docker/scout-action@v1
        with:
          command: cves,recommendations,compare,sbom
          image: ${{ steps.set-image.outputs.IMAGE }}  # Fixed: Using the set-image output
          only-severities: critical,high # only show critical and high CVEs
          only-fixed: true # filter to fixed CVEs
          exit-code: false  # fail or not based on CVEs found?
          sarif-file: sca_scout.sarif
          output: sbom_scout.spdx.json
          format: spdx

      - name: Upload SBOM file as an artifact
        uses: actions/upload-artifact@v4
        with:
          name: sbom_scout.spdx.json
          path: sbom_scout.spdx.json

      - name: Upload SARIF file as an artifact
        uses: actions/upload-artifact@v4
        with:
          name: sca_scout.sarif
          path: sca_scout.sarif

      # Only available on Github Enterprise or public repositories
      - name: Upload SARIF file
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: sca_scout.sarif
          category: Security/SCA

      - name: SBOM upload
        uses: advanced-security/spdx-dependency-submission-action@v0.1.1

      - name: Create success scan file
        run: |
          echo "${{ steps.set-image.outputs.IMAGE }}" >> successful_run.txt

      - name: Upload success scan file
        uses: actions/upload-artifact@v4
        with:
          name: successful_run.txt
          path: successful_run.txt
